export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';

export const GET_POST_DETAIL_REQUEST = "GET_POST_DETAIL_REQUEST";
export const GET_POST_DETAIL_SUCCESS = "GET_POST_DETAIL_SUCCESS";
export const GET_POST_DETAIL_FAILURE = "GET_POST_DETAIL_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS  = "GET_USER_SUCCESS ";
export const GET_USER_FAILURE = "GET_USER_FAILURE";




